In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
dataset = pd.read_csv('~/work/note/ML/Data.csv')

In [9]:
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


#### y - inspected value
#### x - data model

In [10]:
x = dataset.iloc[:,:-1].values

In [11]:
y = dataset.iloc[:,-1].values

#### Transforming missing values

In [13]:
from sklearn.preprocessing import Imputer

In [14]:
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)

In [15]:
cleanResult = imputer.fit(x[:, 1:3])

In [16]:
x[:, 1:3] = cleanResult.transform(x[:, 1:3])

In [17]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


#### Transforming text to index (Encoding categorical data)

In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [19]:
labelEncoder_X = LabelEncoder()

In [20]:
x[:, 0] = labelEncoder_X.fit_transform(x[:,0])

In [21]:
print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


#### Transformin indexex to columns with 1 & 0

In [22]:
oneHotEncoder = OneHotEncoder(categorical_features=[0])

In [23]:
x = oneHotEncoder.fit_transform(x).toarray()

In [24]:
print(y)

In [25]:
labelEncoder_Y = LabelEncoder()

In [26]:
y = labelEncoder_Y.fit_transform(y)

In [27]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


#### Splitting dataset Training set and Test set

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_traint, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

#### Feature scaling

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
sc_x = StandardScaler()

In [32]:
x_traint = sc_x.fit_transform(x_traint)

In [33]:
x_test = sc_x.transform(x_test)

_Dummy variables scale and lose identity?_

In [34]:
print(x_test)

[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
